aws_region        = "us-east-1"
state_bucket_name = "balaji-terraform-state-bucket"
lock_table_name   = "terraform-lock-table"
state_key         = "ec2/terraform.tfstate"

ami_id            = "ami-0360c520857e3138f"
instance_type     = "t2.micro"
subnet_id         = "subnet-06c9e2b72adc9594b"
key_pair_name     = "balaji-keypair"
instance_name     = "TerraformEC2Demo"
environment       = "dev"
